### ISSUE TITLE
Divergenz in Library-Versionen zwischen OpenCMS 13.0 und IDE Connector 2.2.1

### ISSUE THREAD

**Issue by interone-ms** [mediaworx/opencms-ideconnector#19]
Hallo,

beim Update unserer OpenCMS Installation auf v13 ist uns aufgefallen, dass der IDE-Connector auch in der aktuellen Version einen Haufen JARs mit sich schleppt und im OpenCMS WEB-INF/lib Verzeichnis ablegt:
[https://github.com/mediaworx/opencms-ideconnector/tree/master/service/src/main/vfs/system/modules/com.mediaworx.opencms.ideconnector/lib](https://github.com/mediaworx/opencms-ideconnector/tree/master/service/src/main/vfs/system/modules/com.mediaworx.opencms.ideconnector/lib)
 
Allerdings bringt OpenCMS 13 (und ich glaube, auch die 12) zumindest vier der Bibliotheken bereits mit (siehe auch https://github.com/alkacon/opencms-core/blob/build_13_0_0/dependencies.gradle):
$ ls WEB-INF/lib/|grep 'asm\|jackson'
asm-7.2.jar
jackson-annotations-2.11.2.jar
jackson-core-2.11.2.jar
jackson-databind-2.11.2.jar
 
Das Problem ist jetzt ein Versions-Mismatch, einmal ist OpenCMS älter als der IDE Connector, einmal umgekehrt:
asm: OCMS v13 => 7.2, IDE-Connector => 5.1
Jackson: OCMS v13 => 2.13, IDE-Connector => 2.11.2
 
Können Sie bitte die Dependencies einmal angleichen (oder die vier, die OpenCMS mitliefert, zumindest nicht „doppelt“ ablegen)?

**Comment by interone-ms** [comment]
Auch die OpenCMS 12.0 bringt bereits asm 7.2 und die drei jackson-JARs mit, nur mit Jackson 2.11.2 (das sind dieselben, die Sie bereits jetzt shippen), siehe https://github.com/alkacon/opencms-core/blob/build_12_0_0/dependencies.gradle.

Die 11.0.0 bis 11.0.2 bringen nur asm 6.0 mit, jackson fehlt hier komplett.

Die 10er Serie von 10.0.0 bis 10.5.4.4 bringt asm 5.0.3 mit, jackson fehlt auch da. Ich fürchte fast, um eine separate Modul-Version pro OpenCMS Major-Version führt am Ende kein Weg vorbei.

**Comment by kaiwidmann** [comment]
Die Versionen wurden allesamt so aktualisiert, dass sie zu OpenCms 17 passen bzw. gar nicht erst im Modul integriert werden. Tatsächlich müsste man eigentlich den ganzen Zoo an Utilities (xmlutils, manifestgenerator, modulepackager, ideconnector, plugin) auf die jeweilige OpenCms-Version anpassen. Problematisch wird es ggf. bei Jackson-Paketen, wenn diese nicht zu den mit OpenCms gelieferten Versionsnummern passen. 
Falls das mit OpenCms 17 jetzt nicht passt, dann wäre natürlich eine Anpassung an OpenCms 13 auch möglich. Das wäre dann aber ggf. in einem Branch oder einem Fork sinnvoll. Einen Branch dazu gibt es bereits, ich könnte auch ein IDEConnector-Modul liefern, das bei mir mit OpenCms lief. Bei Bedarf einfach nochmal direkt melden.

**Comment by kaiwidmann** [comment]
Ein Modul-Zip für Version 13 liegt auch im Branch: com.mediaworx.opencms.ideconnector_13.0.zip bzw. com.mediaworx.opencms.ideconnector_2.2.1.zip (ich glaube beide Versionen waren identisch, ich habe mich erst nachträglich entschieden, jetzt einfach die OpenCms-Versionsnummer zu verwenden).
