### ISSUE TITLE
https auf Maven-Repository defekt

### ISSUE THREAD

**Issue by interone-ms** [mediaworx/opencms-ideconnector#20]
Beim Bauen des service Moduls ist mir aufgefallen, dass das Repository für die Plugin-Dependency `com.mediaworx.mojo:opencms-maven-plugin` nicht referenziert ist (PR hierzu folgt in Kürze).

Das Repository http://opencms.mediaworx.com/artifactory/opencms-public/ ist nur per HTTP erreichbar, HTTPS ist fehlkonfiguriert (das SSL-Zertifikat hat keinen passenden SAN hinterlegt), was mit aktuellen Maven Versionen zu einem Fehler führt (siehe https://maven.apache.org/docs/3.8.1/release-notes.html).

**Comment by kaiwidmann** [comment]
https://mediaworx.com/ocms-plugin-repository/ funktioniert wieder. Es gibt aktuell Bestrebungen, das alles auf Maven Central bereitzustellen, wann das so weit ist, kann ich aber nicht prognostizieren.
